import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className={`flex flex-col items-center min-h-screen min-w-screen `}>
          <div className="flex align-center justify-center h-[200px] w-full top-bar">
            <Image
              aria-hidden
              src="/logo.svg"
              alt="Logo icon"
              width={226}
              height={48}
            />
          </div>
          <div className="w-full max-w-[736px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
